### ISSUE TITLE
rpi-security.service: control process exited, code=exited status=161

### ISSUE THREAD

**Issue by andrewoverton** [FutureSharks/rpi-security#20]
Hello FutureSharks, I'm trying to install this software and I keep seeing this output when I enter the `sudo systemctl start rpi-security.service` command: 

```
rpi-security.service: control process exited, code=exited status=161
Unit rpi-security.service entered failed state.
```

Do you know how I might be able to troubleshoot this issue? 

Thanks for your help!

**Comment by andrewoverton** [comment]
I think it's because I'm using the Raspberry Pi 3 Model B and its wifi chip doesn't support monitor mode :(

**Comment by FutureSharks** [comment]
Hi Andrew,
If you run `service rpi-security status` it should show you the messages from the service. Does it say there that the device doesn't support monitor mode? I don't think it does:
https://wireless.wiki.kernel.org/en/users/drivers/brcm80211
You will need to get a USB device but they are cheap and easy to find.
Thanks!
Max
