### ISSUE TITLE
usb camera 

### ISSUE THREAD

**Issue by DavidCapek** [FutureSharks/rpi-security#21]
Hello I would wanna ask how to modify the code to make it work with a usb camera.

**Comment by FutureSharks** [comment]
Hi davcap321,
You would need to fork the repo, change any reference to picamera to whatever works with your USB camera and rewrite the `take_photo`  and `take_gif` functions. Perhaps OpenCV might be a good option.
Thanks,
Max

**Comment by DavidCapek** [comment]
Thank you, I have edited The Code but the responding service doesn't start

**Comment by FutureSharks** [comment]
OK, and?

**Comment by projectdrone2** [comment]
@davcap321 , did you manage to make it work with USB Cam?
I went to your fork (https://github.com/davcap321/rpi-security) but could not identify what modification you made.
Thanks
