### ISSUE TITLE
PIR PIN number issue

### ISSUE THREAD

**Issue by linzack** [FutureSharks/rpi-security#23]
Hi,
according to [this article](http://raspberrypi.stackexchange.com/questions/12966/what-is-the-difference-between-board-and-bcm-for-gpio-pin-numbering),
**GPIO.setmode(GPIO.BCM)** and **GPIO.setmode(GPIO.BOARD)** are different in PIN number meaning...
so if user set the PIN number by simply counting, he/she will not get PIR pin to work correctly XD

Does picamera library really need **GPIO.setmode(GPIO.BCM)** mode? It's a bit confusing~~

Nice project, thank you for sharing!!

edit: I'm using RPi3 board...it seems like GPIO.BCM have different pin number across board version

**Comment by FutureSharks** [comment]
Hi linzack,
You are right, I should change this. I'll make a PR soon.
Thanks!

**Comment by linzack** [comment]
Thank you !!
I've changed my pin setting to GPIO.BCM mode, and it worked great!
Integrate with telegram bot is a clever idea, I was wondering how to let Pi send notification to mobile phone, then I found your project...cool

**Comment by FutureSharks** [comment]
I tried it but there is a number of issues.

First thing is that when using `BOARD` mode, [you cannot turn of the camera LED](http://picamera.readthedocs.io/en/release-1.10/recipes1.html#controlling-the-led). The LED is quite annoying to have on IMO.

Second issue is this:
```
Traceback (most recent call last):
  File "/usr/local/bin/rpi-security.py", line 502, in <module>
    GPIO.setup(config['pir_pin'], GPIO.IN)
ValueError: The channel sent is invalid on a Raspberry Pi
```
I had 8 set as the pir_pin.

How did you get it to work without an error?

**Comment by linzack** [comment]
XD I think raspberry noticed the led blink issue, they removed led on Pi Camera v2, but the power/action led are still bright in the night lol.
OK, so pin 32 is the camera led controller?
`GPIO.setup(32, GPIO.OUT, initial=False)`
GPIO32 is not listed on [pin diagram](http://pi4j.com/images/j8header-a-plus-large.png), guess that is built in BRCM firmware, then there is no other way out XD.

The second issue, is your pin 8 in model A+ "BRCM mode GPIO_15, BOARD mode 8"? The response look like a high impedance state in gpio pin. If the gpio input pin is driven by an external circuit, its voltage level will be set up to a "logic 0" or "logic 1" state normally; if the pin is not driven, its state will be floating (or say high impedance), neither "logic 0" nor "logic 1".

I actually comment out some lines to get it work XD. If bypass the camera led problem, set to `GPIO.setmode(GPIO.BOARD)` can still have PIR and camera, in my case [RPi3](https://www.myelectronicslab.com/wp-content/uploads/2016/06/raspbery-pi-3-gpio-pinout-40-pin-header-block-connector-1-1.png), I use pin 11 (BRCM mode GPIO_17, BOARD mode 11) connect PIR sensor pin.
The problem I encountered is camera exception, but can comment it out XD.
`except Exception as e:
exit_error('Camera module failed to intialise with error %s' % e)`
log
`CRITICAL rpi-security_orig_test01.py:404 MainThread          Camera module failed to intialise with error A different mode has already been set!`
When it worked, PIR `motion_detected()` can trigger camera to take picture.

Here is the code I modified.
[rpi-security_orig_test01.txt](https://github.com/FutureSharks/rpi-security/files/722121/rpi-security_orig_test01.txt)

BTW, maybe `GPIO.setmode(GPIO.BCM)` can be resolved if add a gpio pin translation function. HAHA

**Comment by FutureSharks** [comment]
OK then I think the options are:
1. Don't change anything and add a comment in README.md about pin naming.
2. Change mode to BCM and lose ability to disable camera LED.

To be honest I think I'm leaning towards option 1.

Also in about a week I think I will have a version to test that uses the camera for motion detection instead of the PIR sensor.

**Comment by linzack** [comment]
Option 1 is reasonable. Camera motion detection is great!

**Comment by FutureSharks** [comment]
I've updated the README with a note about this issue and included two links to diagrams that show the mapping.
Thanks for pointing it out, @linzack!
