### ISSUE TITLE
Horizontal Flip issue

### ISSUE THREAD

**Issue by mbrownzopa** [FutureSharks/rpi-security#24]
Hi, great project and working really well here.

However one thing I cannot resolve is the Horizontal Flip of the image..
I have tried everything but to no avail. The image is Horizontally flipped the wrong way.

Have you come across this? 

Thanks

**Comment by mbrownzopa** [comment]
As if by magic, it has just started to work! However I did have to add a line of code to the .py script to include hflip and also use uppercase T for True in the conf.

Thanks.

**Comment by FutureSharks** [comment]
You are right! There is a line missing. I'll leave this open until I fix it.

**Comment by FutureSharks** [comment]
Fixed here: https://github.com/FutureSharks/rpi-security/pull/25
Let me know if it doesn't work and thanks for reporting the issue!
