### ISSUE TITLE
Configuration error: KeyError(2,)

### ISSUE THREAD

**Issue by bbregu** [FutureSharks/rpi-security#31]
I installed it using the steps in the guide but keep getting this error :

**pi@raspberrypi:~ $ sudo rpi-security.py -d

2018-03-19 23:12:48 DEBUG   rpis_security.py:69           MainThread                Data file read: /var/lib/rpi-security/data.yaml
2018-03-19 23:12:49 CRITICAL exit_clean.py:22           MainThread                Configuration error: KeyError(2,)**

Any idea what might be wrong?

Thanks!

**Comment by avibe948** [comment]
Same issue for me. 
In addition probably requires another ticket - need to add support to a standard usb camera. Can help to write the code if not already supported

**Comment by FutureSharks** [comment]
@bbregu can you run these commands right before you run `sudo rpi-security.py -d`?

```
ifconfig -a
iwconfig
```

**Comment by avibe948** [comment]
I tried that and it still throws the same error.
I use a usb camera and looking at your code it is written for pi camera only. I can change the code or use another GitHub project and utilise some of the features you wrote.

**Comment by FutureSharks** [comment]
No, I want you to run those commands and paste all the output here.

If you are using a USB camera then this project won't work for you, sorry.

**Comment by FutureSharks** [comment]
Hey, I updated the readme with some missing packages:
https://github.com/FutureSharks/rpi-security/commit/506738fcdd23585b3663a28404bd2a8235bb050d

Could you retest?
