### ISSUE TITLE
Raspberry PI 4 - Pillow error

### ISSUE THREAD

**Issue by MrFramboise** [FutureSharks/rpi-security#50]
Hello,

First of all : Thanks it's a fantastic project you have and I would be so happy to implement it at home.

I have a fresh Buster install and when I try to follow your tuto I face an error message about pillow.
Please find the error below :

Could you tell me what I do wrong ?
Thanks in advance

`pi@raspberrypi:~ $ sudo pip3 install --no-binary :all: https://github.com/FutureSharks/rpi-security/archive/1.4.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/FutureSharks/rpi-security/archive/1.4.zip
  Downloading https://github.com/FutureSharks/rpi-security/archive/1.4.zip
     \ 4.0MB 64.8MB/s
Collecting Pillow==6.2.1 (from rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/5b/bb/cdc8086db1f15d0664dd22a62c69613cdc00f1dd430b5b19df1bea83f2a3/Pillow-6.2.1.tar.gz (37.7MB)
    100% |████████████████████████████████| 37.7MB 11kB/s 
Collecting configparser (from rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/16/4f/48975536bd488d3a272549eb795ac4a13a5f7fcdc8995def77fbef3532ee/configparser-4.0.2.tar.gz (72kB)
    100% |████████████████████████████████| 81kB 427kB/s 
  Installing build dependencies ... done
Collecting imutils==0.5.2 (from rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/5e/0c/659c2bdae8e8ca5ef810b9da02db28feaa29ea448ff36b65a1664ff28142/imutils-0.5.2.tar.gz
Collecting netaddr (from rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/0c/13/7cbb180b52201c07c796243eeff4c256b053656da5cfe3916c3f5b57b3a0/netaddr-0.7.19.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 251kB/s 
Collecting netifaces (from rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/0d/18/fd6e9c71a35b67a73160ec80a49da63d1eed2d2055054cc2995714949132/netifaces-0.10.9.tar.gz
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from rpi-security==1.4) (1.16.2)
Requirement already satisfied: opencv-contrib-python in /usr/local/lib/python3.7/dist-packages (from rpi-security==1.4) (4.1.1.26)
Requirement already satisfied: opencv-contrib-python-headless in /usr/local/lib/python3.7/dist-packages (from rpi-security==1.4) (4.1.1.26)
Requirement already satisfied: picamera==1.13 in /usr/lib/python3/dist-packages (from rpi-security==1.4) (1.13)
Collecting python-telegram-bot==12.2.0 (from rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/70/ce/da26173402f5714e29958dcf24202b24ad22fe5f4cb3427072a163072f56/python-telegram-bot-12.2.0.tar.gz (234kB)
    100% |████████████████████████████████| 235kB 1.5MB/s 
Collecting pyyaml (from rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
    100% |████████████████████████████████| 266kB 1.3MB/s 
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from rpi-security==1.4) (2.21.0)
Collecting scapy==2.4.3 (from rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/52/e7/464079606a9cf97ad04936c52a5324d14dae36215f9319bf3faa46a7907d/scapy-2.4.3.tar.gz (905kB)
    100% |████████████████████████████████| 911kB 437kB/s 
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from python-telegram-bot==12.2.0->rpi-security==1.4) (2018.8.24)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from python-telegram-bot==12.2.0->rpi-security==1.4) (2.6.1)
Collecting future>=0.16.0 (from python-telegram-bot==12.2.0->rpi-security==1.4)
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 499kB/s 
Requirement already satisfied: tornado>=5.1 in /usr/lib/python3/dist-packages (from python-telegram-bot==12.2.0->rpi-security==1.4) (5.1.1)
Skipping bdist_wheel for rpi-security, due to binaries being disabled for it.
Skipping bdist_wheel for Pillow, due to binaries being disabled for it.
Skipping bdist_wheel for configparser, due to binaries being disabled for it.
Skipping bdist_wheel for imutils, due to binaries being disabled for it.
Skipping bdist_wheel for netaddr, due to binaries being disabled for it.
Skipping bdist_wheel for netifaces, due to binaries being disabled for it.
Skipping bdist_wheel for python-telegram-bot, due to binaries being disabled for it.
Skipping bdist_wheel for pyyaml, due to binaries being disabled for it.
Skipping bdist_wheel for scapy, due to binaries being disabled for it.
Skipping bdist_wheel for future, due to binaries being disabled for it.
Installing collected packages: Pillow, configparser, imutils, netaddr, netifaces, future, python-telegram-bot, pyyaml, scapy, rpi-security
  Found existing installation: Pillow 5.4.1
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Pillow'. No files were found to uninstall.
  Running setup.py install for Pillow ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-djbvaq6m/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3io734hb/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    creating build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/features.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_version.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_util.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Image.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-djbvaq6m/Pillow/setup.py", line 888, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW),
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-djbvaq6m/Pillow/setup.py", line 687, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-djbvaq6m/Pillow/setup.py", line 903, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
  Can't roll back Pillow; was not uninstalled
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-djbvaq6m/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3io734hb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-djbvaq6m/Pillow/`

**Comment by FutureSharks** [comment]
Hi @MrFramboise 

Did you install the apk packages listed in the README? https://github.com/FutureSharks/rpi-security#installation-configuration-and-running

```
sudo apt update

sudo apt install -y libhdf5-100 libharfbuzz0b libwebp6 libjasper1 libilmbase12 libopenexr22 libgstreamer1.0-0 libavcodec-extra57 libavformat57 libswscale4 libgtk-3-0 libqtgui4 libqt4-test libatlas-base-dev tcpdump iw python3-dev python3-pip libjpeg8-dev zlib1g-dev libffi-dev python3-numpy libopenjp2-7-dev libtiff5
```

**Comment by Javier-free** [comment]
Hello,
I have the same problem that MrFramboise  and i can´t install the packages list, this is the result:
Thanks in advance

Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
El paquete libavcodec-extra57 no está disponible, pero algún otro paquete hace r                              eferencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

El paquete libhdf5-100 no está disponible, pero algún otro paquete hace referenc                              ia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente
Sin embargo, los siguientes paquetes lo reemplazan:
  libhdf5-103

El paquete libopenexr22 no está disponible, pero algún otro paquete hace referen                              cia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente
Sin embargo, los siguientes paquetes lo reemplazan:
  libopenexr23

E: El paquete «libhdf5-100» no tiene un candidato para la instalación
E: No se ha podido localizar el paquete libilmbase12
E: El paquete «libopenexr22» no tiene un candidato para la instalación
E: El paquete «libavcodec-extra57» no tiene un candidato para la instalación
E: No se ha podido localizar el paquete libavformat57
E: No se ha podido localizar el paquete libswscale4

**Comment by FutureSharks** [comment]
Hi @Javier-free 
Can you test my updated instructions in this PR? https://github.com/FutureSharks/rpi-security/pull/52/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by Javier-free** [comment]
Hi,
The same result, cannot find the packages to install:

I had the project running 3 years ago, and it seemed like a great project, but after a hardware breakdown I can't reinstall it.

pi@raspberrypi:~ $ sudo apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
pi@raspberrypi:~ $ sudo apt install -y libhdf5-100 libharfbuzz0b libwebp6 libjasper1 libilmbase12 libopenexr22 libgstreamer1.0-0 libavcodec-extra57 libavformat57 libswscale4 libgtk-3-0 libqtgui4 libqt4-test libatlas-base-dev tcpdump iw python3-dev python3-pip libjpeg8-dev zlib1g-dev libffi-dev python3-numpy libopenjp2-7-dev libtiff5
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libavcodec-extra57 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libhdf5-100 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libhdf5-103

Package libopenexr22 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libopenexr23

E: Package 'libhdf5-100' has no installation candidate
E: Unable to locate package libilmbase12
E: Package 'libopenexr22' has no installation candidate
E: Package 'libavcodec-extra57' has no installation candidate
E: Unable to locate package libavformat57
E: Unable to locate package libswscale4
pi@raspberrypi:~ $

**Comment by FutureSharks** [comment]
@Javier-free you haven't followed the new instructions in that output. I'll paste it for you:


```console
sudo apt install -y libhdf5-103 libharfbuzz0b libwebp6 libjasper1 libopenexr23 libgstreamer1.0-0 libatlas-base-dev libgtk-3-0 libqtgui4 libqt4-test libilmbase23 libavcodec-extra58 libavformat58 libswscale5  libjpeg8-dev zlib1g-dev libffi-dev libopenjp2-7-dev libtiff5
```

```console
sudo pip3 install opencv-contrib-python==3.4.6.27 opencv-contrib-python-headless==3.4.6.27
sudo pip3 install --no-binary :all: https://github.com/FutureSharks/rpi-security/archive/1.4.zip
```

**Comment by Javier-free** [comment]
Hello, big breakthrough
I am a fool did not understand the meaning of the red and green lines.
The truth is that for my Linux it is a strange and dark world. I admire those who dominate it.
Thanks for everything,

**Comment by FutureSharks** [comment]
Haha OK
